import { Tag } from './tag.model';

export interface Bookmark {
  id: string;
  title: string;
  description: string;
  image: string | null;
  /* author: string; */
  type: string | null;
  url: string;
  domain: string;
  canonicalUrl: string;
  followsRedirect: boolean;
  user_id: string;
  contentInMarkdown: string;
  tags?: Tag[];
  // auto-generated by mongoose timestamp option
  created_at?: string;
  updated_at?: string;

  // fields added by mongoose_delete plugin
  deleted?: false;
}
